[package]
name = "custom-tv-show-namer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "plex"
path = "examples/plex.rs"
required-features = ["plex"]

[[example]]
name = "custom"
path = "examples/custom_struct.rs"
required-features = ["tnp"]

[features]
tnp = ["torrent-name-parser"]
#titlecase = ["titlecase"]
plex = ["torrent-name-parser", "titlecase"]

[dependencies]
titlecase = { version = "1.1.0", optional = true }
torrent-name-parser = { version = "0.10.0", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
