[package]
name = "custom-tv-show-namer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
titlecase = "1.1.0"
torrent-name-parser = "0.10.0"
